name: device_uid
description: A Flutter plugin to retrieve a unique device ID natively without third-party dependencies.
version: 1.0.2
homepage: https://pub.dev/publishers/techlinkmyanmar.com/packages
repository: https://github.com/thethtwe-dev/device_uid

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: com.thethtwe.device_uid
        pluginClass: DeviceUidPlugin
      ios:
        pluginClass: DeviceUidPlugin